const express  = require("express");
const  { getCart,  addToCart, deleteCartItem, cartTotal, totalItems, clearCart, incrementCartItem, decrementCartItem, getUserCartItems, deleteCartItemByAdmin, applyCouponCode } = require("../controllers/cartController");
const protect = require("./../middleware/authMiddleware");
const isAdmin = require("./../middleware/adminMiddleware");
const router = express.Router();
router.get('/', protect, getCart);
router.post('/add-to-cart', protect, addToCart);
router.post("/", protect, deleteCartItem);
router.get("/cart-total", protect, cartTotal);
router.get("/total-items", protect, totalItems);
router.get("/clear-cart", protect, clearCart);
router.put("/increment", protect, incrementCartItem);
router.put("/decrement", protect, decrementCartItem);
router.get("/admin/cartItems", isAdmin, getUserCartItems);
router.post("/admin/delete-cart-item", isAdmin, deleteCartItemByAdmin);
router.post("/applycode", protect, applyCouponCode);
module.exports = router;