const express = require("express");
const { getOrganizerEvents, createEventByOrganizer, deleteEventByOrganizer, updateEventStatusByOrganizer, updateEventByOrganizer, getEvents } = require("../controllers/eventController");
const  isOrganizer  = require("./../middleware/organizerMiddleware");
const { upload } = require("../utils/fileUpload");
const router = express.Router();
router.get("/", getEvents);
router.get("/", isOrganizer, getOrganizerEvents);
router.post("/", isOrganizer, upload.single("image"), createEventByOrganizer);
router.post("/update", isOrganizer, updateEventStatusByOrganizer);
router.put("/update_event", isOrganizer, updateEventByOrganizer);
router.get("/:id", isOrganizer, deleteEventByOrganizer);
module.exports = router;